version: "3.9"

services:
  # база для основного сервиса
  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    ports:
      - "5430:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewm -d ewm" ]
      interval: 3s
      timeout: 5s
      retries: 20

  # база для сервиса статистики
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stats -d stats" ]
      interval: 3s
      timeout: 5s
      retries: 20

  # сервис статистики
  stats-server:
    build:
      context: ./ewm-stat/ewm-stat-service
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 9090
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9090/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  # основной сервис ewm
  ewm-service:
    build:
      context: ./ewm-main/ewm-main-service
      dockerfile: Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      STATS_BASE_URL: http://stats-server:9090
      STATS_URL: http://stats-server:9090
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL","wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 30s
