CREATE SCHEMA IF NOT EXISTS schema;
SET search_path TO schema;


CREATE TABLE location
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);
CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL

);

CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name  VARCHAR(255) NOT NULL
);



CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         TEXT         NOT NULL,
    category_id        BIGINT       NOT NULL,
    confirmed_requests BIGINT                DEFAULT 0,
    created_on         TIMESTAMP    NOT NULL DEFAULT now(),
    description        TEXT         NOT NULL,
    event_date         TIMESTAMP    NOT NULL,
    initiator_id       BIGINT       NOT NULL,
    location_id        BIGINT       NOT NULL,
    paid               BOOLEAN               DEFAULT FALSE,
    participant_limit  INTEGER               DEFAULT 0,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN               DEFAULT TRUE,
    state              VARCHAR(50),
    title              VARCHAR(255) NOT NULL,
    views              BIGINT                DEFAULT 0,
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (initiator_id) REFERENCES users (id),
    FOREIGN KEY (location_id) REFERENCES location (id)


);
CREATE TABLE participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP   NOT NULL,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL,
    status       VARCHAR(50) NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN      NOT NULL,
    title  VARCHAR(255) NOT NULL
);


CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);





